//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace SOS.Phone.GroupServiceRef {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupList", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class GroupList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.ResultInfo> DataInfoField;
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.ResultInfo> DataInfo {
            get {
                return this.DataInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataInfoField, value) != true)) {
                    this.DataInfoField = value;
                    this.RaisePropertyChanged("DataInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultInfo", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts.OutB" +
        "ound")]
    public partial class ResultInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string MessageField;
        
        private SOS.Phone.GroupServiceRef.ResultTypeEnum ResultTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOS.Phone.GroupServiceRef.ResultTypeEnum ResultType {
            get {
                return this.ResultTypeField;
            }
            set {
                if ((this.ResultTypeField.Equals(value) != true)) {
                    this.ResultTypeField = value;
                    this.RaisePropertyChanged("ResultType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class Group : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool AllowGroupManagementField;
        
        private string EmailField;
        
        private string EnrollmentKeyField;
        
        private SOS.Phone.GroupServiceRef.Enrollment EnrollmentTypeField;
        
        private string EnrollmentValueField;
        
        private string GeoLocationField;
        
        private string GroupIDField;
        
        private string GroupLocationField;
        
        private string GroupNameField;
        
        private bool IsActiveField;
        
        private bool IsValidatedField;
        
        private SOS.Phone.GroupServiceRef.LiveCred LiveInfoField;
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Profile> MembersField;
        
        private bool NotifySubgroupsField;
        
        private System.Nullable<int> ParentGroupIDField;
        
        private string PhoneNumberField;
        
        private string ShapeFileIDField;
        
        private bool ShowIncidentsField;
        
        private string SubGroupIdentificationKeyField;
        
        private bool ToRemoveField;
        
        private SOS.Phone.GroupServiceRef.GroupType TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool AllowGroupManagement {
            get {
                return this.AllowGroupManagementField;
            }
            set {
                if ((this.AllowGroupManagementField.Equals(value) != true)) {
                    this.AllowGroupManagementField = value;
                    this.RaisePropertyChanged("AllowGroupManagement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnrollmentKey {
            get {
                return this.EnrollmentKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EnrollmentKeyField, value) != true)) {
                    this.EnrollmentKeyField = value;
                    this.RaisePropertyChanged("EnrollmentKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOS.Phone.GroupServiceRef.Enrollment EnrollmentType {
            get {
                return this.EnrollmentTypeField;
            }
            set {
                if ((this.EnrollmentTypeField.Equals(value) != true)) {
                    this.EnrollmentTypeField = value;
                    this.RaisePropertyChanged("EnrollmentType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnrollmentValue {
            get {
                return this.EnrollmentValueField;
            }
            set {
                if ((object.ReferenceEquals(this.EnrollmentValueField, value) != true)) {
                    this.EnrollmentValueField = value;
                    this.RaisePropertyChanged("EnrollmentValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GeoLocation {
            get {
                return this.GeoLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoLocationField, value) != true)) {
                    this.GeoLocationField = value;
                    this.RaisePropertyChanged("GeoLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupIDField, value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupLocation {
            get {
                return this.GroupLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupLocationField, value) != true)) {
                    this.GroupLocationField = value;
                    this.RaisePropertyChanged("GroupLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValidated {
            get {
                return this.IsValidatedField;
            }
            set {
                if ((this.IsValidatedField.Equals(value) != true)) {
                    this.IsValidatedField = value;
                    this.RaisePropertyChanged("IsValidated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SOS.Phone.GroupServiceRef.LiveCred LiveInfo {
            get {
                return this.LiveInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.LiveInfoField, value) != true)) {
                    this.LiveInfoField = value;
                    this.RaisePropertyChanged("LiveInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Profile> Members {
            get {
                return this.MembersField;
            }
            set {
                if ((object.ReferenceEquals(this.MembersField, value) != true)) {
                    this.MembersField = value;
                    this.RaisePropertyChanged("Members");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool NotifySubgroups {
            get {
                return this.NotifySubgroupsField;
            }
            set {
                if ((this.NotifySubgroupsField.Equals(value) != true)) {
                    this.NotifySubgroupsField = value;
                    this.RaisePropertyChanged("NotifySubgroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> ParentGroupID {
            get {
                return this.ParentGroupIDField;
            }
            set {
                if ((this.ParentGroupIDField.Equals(value) != true)) {
                    this.ParentGroupIDField = value;
                    this.RaisePropertyChanged("ParentGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShapeFileID {
            get {
                return this.ShapeFileIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ShapeFileIDField, value) != true)) {
                    this.ShapeFileIDField = value;
                    this.RaisePropertyChanged("ShapeFileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool ShowIncidents {
            get {
                return this.ShowIncidentsField;
            }
            set {
                if ((this.ShowIncidentsField.Equals(value) != true)) {
                    this.ShowIncidentsField = value;
                    this.RaisePropertyChanged("ShowIncidents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SubGroupIdentificationKey {
            get {
                return this.SubGroupIdentificationKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SubGroupIdentificationKeyField, value) != true)) {
                    this.SubGroupIdentificationKeyField = value;
                    this.RaisePropertyChanged("SubGroupIdentificationKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ToRemove {
            get {
                return this.ToRemoveField;
            }
            set {
                if ((this.ToRemoveField.Equals(value) != true)) {
                    this.ToRemoveField = value;
                    this.RaisePropertyChanged("ToRemove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOS.Phone.GroupServiceRef.GroupType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts.OutB" +
        "ound")]
    public enum ResultTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthError = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiveCred", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class LiveCred : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enrollment", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public enum Enrollment : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AutoOrgMail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Moderator = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class Profile : SOS.Phone.GroupServiceRef.ProfileLite {
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> AscGroupsField;
        
        private bool CanArchiveField;
        
        private bool CanMailField;
        
        private bool CanPostField;
        
        private bool CanSMSField;
        
        private string EnterpriseEmailIDField;
        
        private string EnterpriseSecurityTokenField;
        
        private string FBGroupIDField;
        
        private string FBGroupNameField;
        
        private bool IsValidField;
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.ProfileLite> LocateBuddiesField;
        
        private bool LocationConsentField;
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Buddy> MyBuddiesField;
        
        private string NotificationUriField;
        
        private SOS.Phone.GroupServiceRef.DeviceSetting PhoneSettingField;
        
        private string PrimeGroupIDField;
        
        private string SecurityTokenField;
        
        private SOS.Phone.GroupServiceRef.PortalSetting SiteSettingField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> AscGroups {
            get {
                return this.AscGroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.AscGroupsField, value) != true)) {
                    this.AscGroupsField = value;
                    this.RaisePropertyChanged("AscGroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanArchive {
            get {
                return this.CanArchiveField;
            }
            set {
                if ((this.CanArchiveField.Equals(value) != true)) {
                    this.CanArchiveField = value;
                    this.RaisePropertyChanged("CanArchive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanMail {
            get {
                return this.CanMailField;
            }
            set {
                if ((this.CanMailField.Equals(value) != true)) {
                    this.CanMailField = value;
                    this.RaisePropertyChanged("CanMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanPost {
            get {
                return this.CanPostField;
            }
            set {
                if ((this.CanPostField.Equals(value) != true)) {
                    this.CanPostField = value;
                    this.RaisePropertyChanged("CanPost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanSMS {
            get {
                return this.CanSMSField;
            }
            set {
                if ((this.CanSMSField.Equals(value) != true)) {
                    this.CanSMSField = value;
                    this.RaisePropertyChanged("CanSMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseEmailID {
            get {
                return this.EnterpriseEmailIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseEmailIDField, value) != true)) {
                    this.EnterpriseEmailIDField = value;
                    this.RaisePropertyChanged("EnterpriseEmailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EnterpriseSecurityToken {
            get {
                return this.EnterpriseSecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.EnterpriseSecurityTokenField, value) != true)) {
                    this.EnterpriseSecurityTokenField = value;
                    this.RaisePropertyChanged("EnterpriseSecurityToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBGroupID {
            get {
                return this.FBGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FBGroupIDField, value) != true)) {
                    this.FBGroupIDField = value;
                    this.RaisePropertyChanged("FBGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FBGroupName {
            get {
                return this.FBGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FBGroupNameField, value) != true)) {
                    this.FBGroupNameField = value;
                    this.RaisePropertyChanged("FBGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.ProfileLite> LocateBuddies {
            get {
                return this.LocateBuddiesField;
            }
            set {
                if ((object.ReferenceEquals(this.LocateBuddiesField, value) != true)) {
                    this.LocateBuddiesField = value;
                    this.RaisePropertyChanged("LocateBuddies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LocationConsent {
            get {
                return this.LocationConsentField;
            }
            set {
                if ((this.LocationConsentField.Equals(value) != true)) {
                    this.LocationConsentField = value;
                    this.RaisePropertyChanged("LocationConsent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Buddy> MyBuddies {
            get {
                return this.MyBuddiesField;
            }
            set {
                if ((object.ReferenceEquals(this.MyBuddiesField, value) != true)) {
                    this.MyBuddiesField = value;
                    this.RaisePropertyChanged("MyBuddies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationUri {
            get {
                return this.NotificationUriField;
            }
            set {
                if ((object.ReferenceEquals(this.NotificationUriField, value) != true)) {
                    this.NotificationUriField = value;
                    this.RaisePropertyChanged("NotificationUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOS.Phone.GroupServiceRef.DeviceSetting PhoneSetting {
            get {
                return this.PhoneSettingField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneSettingField, value) != true)) {
                    this.PhoneSettingField = value;
                    this.RaisePropertyChanged("PhoneSetting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimeGroupID {
            get {
                return this.PrimeGroupIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimeGroupIDField, value) != true)) {
                    this.PrimeGroupIDField = value;
                    this.RaisePropertyChanged("PrimeGroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOS.Phone.GroupServiceRef.PortalSetting SiteSetting {
            get {
                return this.SiteSettingField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteSettingField, value) != true)) {
                    this.SiteSettingField = value;
                    this.RaisePropertyChanged("SiteSetting");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupType", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public enum GroupType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Public = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Private = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Social = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOS.Phone.GroupServiceRef.Buddy))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOS.Phone.GroupServiceRef.ProfileLite))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOS.Phone.GroupServiceRef.Profile))]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.ResultInfo> DataInfoField;
        
        private string EmailField;
        
        private string FBAuthIDField;
        
        private string FBIDField;
        
        private SOS.Phone.GroupServiceRef.LiveCred LiveDetailsField;
        
        private string MobileNumberField;
        
        private string NameField;
        
        private string RegionCodeField;
        
        private long UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.ResultInfo> DataInfo {
            get {
                return this.DataInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.DataInfoField, value) != true)) {
                    this.DataInfoField = value;
                    this.RaisePropertyChanged("DataInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FBAuthID {
            get {
                return this.FBAuthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FBAuthIDField, value) != true)) {
                    this.FBAuthIDField = value;
                    this.RaisePropertyChanged("FBAuthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FBID {
            get {
                return this.FBIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FBIDField, value) != true)) {
                    this.FBIDField = value;
                    this.RaisePropertyChanged("FBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public SOS.Phone.GroupServiceRef.LiveCred LiveDetails {
            get {
                return this.LiveDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.LiveDetailsField, value) != true)) {
                    this.LiveDetailsField = value;
                    this.RaisePropertyChanged("LiveDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionCode {
            get {
                return this.RegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionCodeField, value) != true)) {
                    this.RegionCodeField = value;
                    this.RaisePropertyChanged("RegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Buddy", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class Buddy : SOS.Phone.GroupServiceRef.User {
        
        private long BuddyIDField;
        
        private bool IsPrimeBuddyField;
        
        private SOS.Phone.GroupServiceRef.BuddyState StateField;
        
        private System.Nullable<System.Guid> SubscribtionIDField;
        
        private bool ToRemoveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BuddyID {
            get {
                return this.BuddyIDField;
            }
            set {
                if ((this.BuddyIDField.Equals(value) != true)) {
                    this.BuddyIDField = value;
                    this.RaisePropertyChanged("BuddyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPrimeBuddy {
            get {
                return this.IsPrimeBuddyField;
            }
            set {
                if ((this.IsPrimeBuddyField.Equals(value) != true)) {
                    this.IsPrimeBuddyField = value;
                    this.RaisePropertyChanged("IsPrimeBuddy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SOS.Phone.GroupServiceRef.BuddyState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> SubscribtionID {
            get {
                return this.SubscribtionIDField;
            }
            set {
                if ((this.SubscribtionIDField.Equals(value) != true)) {
                    this.SubscribtionIDField = value;
                    this.RaisePropertyChanged("SubscribtionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ToRemove {
            get {
                return this.ToRemoveField;
            }
            set {
                if ((this.ToRemoveField.Equals(value) != true)) {
                    this.ToRemoveField = value;
                    this.RaisePropertyChanged("ToRemove");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileLite", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SOS.Phone.GroupServiceRef.Profile))]
    public partial class ProfileLite : SOS.Phone.GroupServiceRef.User {
        
        private bool IsSOSOnField;
        
        private bool IsTrackingOnField;
        
        private System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.GeoTag> LastLocsField;
        
        private long ProfileIDField;
        
        private string SessionIDField;
        
        private string TinyURIField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSOSOn {
            get {
                return this.IsSOSOnField;
            }
            set {
                if ((this.IsSOSOnField.Equals(value) != true)) {
                    this.IsSOSOnField = value;
                    this.RaisePropertyChanged("IsSOSOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTrackingOn {
            get {
                return this.IsTrackingOnField;
            }
            set {
                if ((this.IsTrackingOnField.Equals(value) != true)) {
                    this.IsTrackingOnField = value;
                    this.RaisePropertyChanged("IsTrackingOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.GeoTag> LastLocs {
            get {
                return this.LastLocsField;
            }
            set {
                if ((object.ReferenceEquals(this.LastLocsField, value) != true)) {
                    this.LastLocsField = value;
                    this.RaisePropertyChanged("LastLocs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((this.ProfileIDField.Equals(value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIDField, value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TinyURI {
            get {
                return this.TinyURIField;
            }
            set {
                if ((object.ReferenceEquals(this.TinyURIField, value) != true)) {
                    this.TinyURIField = value;
                    this.RaisePropertyChanged("TinyURI");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeoTag", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class GeoTag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double AccuracyField;
        
        private string AdditionalInfoField;
        
        private string AltField;
        
        private string CommandField;
        
        private string GeoDirectionField;
        
        private System.Nullable<bool> IsSOSField;
        
        private string LatField;
        
        private string LongField;
        
        private byte[] MediaContentField;
        
        private string MediaUriField;
        
        private long ProfileIDField;
        
        private string SessionIDField;
        
        private int SpeedField;
        
        private long TimeStampField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Accuracy {
            get {
                return this.AccuracyField;
            }
            set {
                if ((this.AccuracyField.Equals(value) != true)) {
                    this.AccuracyField = value;
                    this.RaisePropertyChanged("Accuracy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo {
            get {
                return this.AdditionalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfoField, value) != true)) {
                    this.AdditionalInfoField = value;
                    this.RaisePropertyChanged("AdditionalInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alt {
            get {
                return this.AltField;
            }
            set {
                if ((object.ReferenceEquals(this.AltField, value) != true)) {
                    this.AltField = value;
                    this.RaisePropertyChanged("Alt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Command {
            get {
                return this.CommandField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandField, value) != true)) {
                    this.CommandField = value;
                    this.RaisePropertyChanged("Command");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GeoDirection {
            get {
                return this.GeoDirectionField;
            }
            set {
                if ((object.ReferenceEquals(this.GeoDirectionField, value) != true)) {
                    this.GeoDirectionField = value;
                    this.RaisePropertyChanged("GeoDirection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsSOS {
            get {
                return this.IsSOSField;
            }
            set {
                if ((this.IsSOSField.Equals(value) != true)) {
                    this.IsSOSField = value;
                    this.RaisePropertyChanged("IsSOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lat {
            get {
                return this.LatField;
            }
            set {
                if ((object.ReferenceEquals(this.LatField, value) != true)) {
                    this.LatField = value;
                    this.RaisePropertyChanged("Lat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Long {
            get {
                return this.LongField;
            }
            set {
                if ((object.ReferenceEquals(this.LongField, value) != true)) {
                    this.LongField = value;
                    this.RaisePropertyChanged("Long");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] MediaContent {
            get {
                return this.MediaContentField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaContentField, value) != true)) {
                    this.MediaContentField = value;
                    this.RaisePropertyChanged("MediaContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MediaUri {
            get {
                return this.MediaUriField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaUriField, value) != true)) {
                    this.MediaUriField = value;
                    this.RaisePropertyChanged("MediaUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((this.ProfileIDField.Equals(value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionIDField, value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Speed {
            get {
                return this.SpeedField;
            }
            set {
                if ((this.SpeedField.Equals(value) != true)) {
                    this.SpeedField = value;
                    this.RaisePropertyChanged("Speed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeviceSetting", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class DeviceSetting : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool CanEmailField;
        
        private bool CanSMSField;
        
        private string DeviceIDField;
        
        private string PlatFormField;
        
        private string ProfileIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanEmail {
            get {
                return this.CanEmailField;
            }
            set {
                if ((this.CanEmailField.Equals(value) != true)) {
                    this.CanEmailField = value;
                    this.RaisePropertyChanged("CanEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CanSMS {
            get {
                return this.CanSMSField;
            }
            set {
                if ((this.CanSMSField.Equals(value) != true)) {
                    this.CanSMSField = value;
                    this.RaisePropertyChanged("CanSMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceID {
            get {
                return this.DeviceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceIDField, value) != true)) {
                    this.DeviceIDField = value;
                    this.RaisePropertyChanged("DeviceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlatForm {
            get {
                return this.PlatFormField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatFormField, value) != true)) {
                    this.PlatFormField = value;
                    this.RaisePropertyChanged("PlatForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfileID {
            get {
                return this.ProfileIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileIDField, value) != true)) {
                    this.ProfileIDField = value;
                    this.RaisePropertyChanged("ProfileID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortalSetting", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public partial class PortalSetting : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BuddyState", Namespace="http://schemas.datacontract.org/2004/07/SOS.Service.Interfaces.DataContracts")]
    public enum BuddyState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Suspended = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Marshal = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.microsoft.com/sos/2013/02", ConfigurationName="GroupServiceRef.GroupService")]
    public interface GroupService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.microsoft.com/sos/2013/02/GroupService/GetListOfGroups", ReplyAction="http://www.microsoft.com/sos/2013/02/GroupService/GetListOfGroupsResponse")]
        System.IAsyncResult BeginGetListOfGroups(string SearchKey, System.AsyncCallback callback, object asyncState);
        
        SOS.Phone.GroupServiceRef.GroupList EndGetListOfGroups(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.microsoft.com/sos/2013/02/GroupService/GetListOfVolunteerGroups", ReplyAction="http://www.microsoft.com/sos/2013/02/GroupService/GetListOfVolunteerGroupsRespons" +
            "e")]
        System.IAsyncResult BeginGetListOfVolunteerGroups(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> EndGetListOfVolunteerGroups(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GroupServiceChannel : SOS.Phone.GroupServiceRef.GroupService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListOfGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListOfGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SOS.Phone.GroupServiceRef.GroupList Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SOS.Phone.GroupServiceRef.GroupList)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListOfVolunteerGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetListOfVolunteerGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GroupServiceClient : System.ServiceModel.ClientBase<SOS.Phone.GroupServiceRef.GroupService>, SOS.Phone.GroupServiceRef.GroupService {
        
        private BeginOperationDelegate onBeginGetListOfGroupsDelegate;
        
        private EndOperationDelegate onEndGetListOfGroupsDelegate;
        
        private System.Threading.SendOrPostCallback onGetListOfGroupsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetListOfVolunteerGroupsDelegate;
        
        private EndOperationDelegate onEndGetListOfVolunteerGroupsDelegate;
        
        private System.Threading.SendOrPostCallback onGetListOfVolunteerGroupsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public GroupServiceClient() {
        }
        
        public GroupServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GroupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetListOfGroupsCompletedEventArgs> GetListOfGroupsCompleted;
        
        public event System.EventHandler<GetListOfVolunteerGroupsCompletedEventArgs> GetListOfVolunteerGroupsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SOS.Phone.GroupServiceRef.GroupService.BeginGetListOfGroups(string SearchKey, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListOfGroups(SearchKey, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOS.Phone.GroupServiceRef.GroupList SOS.Phone.GroupServiceRef.GroupService.EndGetListOfGroups(System.IAsyncResult result) {
            return base.Channel.EndGetListOfGroups(result);
        }
        
        private System.IAsyncResult OnBeginGetListOfGroups(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string SearchKey = ((string)(inValues[0]));
            return ((SOS.Phone.GroupServiceRef.GroupService)(this)).BeginGetListOfGroups(SearchKey, callback, asyncState);
        }
        
        private object[] OnEndGetListOfGroups(System.IAsyncResult result) {
            SOS.Phone.GroupServiceRef.GroupList retVal = ((SOS.Phone.GroupServiceRef.GroupService)(this)).EndGetListOfGroups(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListOfGroupsCompleted(object state) {
            if ((this.GetListOfGroupsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListOfGroupsCompleted(this, new GetListOfGroupsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListOfGroupsAsync(string SearchKey) {
            this.GetListOfGroupsAsync(SearchKey, null);
        }
        
        public void GetListOfGroupsAsync(string SearchKey, object userState) {
            if ((this.onBeginGetListOfGroupsDelegate == null)) {
                this.onBeginGetListOfGroupsDelegate = new BeginOperationDelegate(this.OnBeginGetListOfGroups);
            }
            if ((this.onEndGetListOfGroupsDelegate == null)) {
                this.onEndGetListOfGroupsDelegate = new EndOperationDelegate(this.OnEndGetListOfGroups);
            }
            if ((this.onGetListOfGroupsCompletedDelegate == null)) {
                this.onGetListOfGroupsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListOfGroupsCompleted);
            }
            base.InvokeAsync(this.onBeginGetListOfGroupsDelegate, new object[] {
                        SearchKey}, this.onEndGetListOfGroupsDelegate, this.onGetListOfGroupsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SOS.Phone.GroupServiceRef.GroupService.BeginGetListOfVolunteerGroups(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetListOfVolunteerGroups(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> SOS.Phone.GroupServiceRef.GroupService.EndGetListOfVolunteerGroups(System.IAsyncResult result) {
            return base.Channel.EndGetListOfVolunteerGroups(result);
        }
        
        private System.IAsyncResult OnBeginGetListOfVolunteerGroups(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SOS.Phone.GroupServiceRef.GroupService)(this)).BeginGetListOfVolunteerGroups(callback, asyncState);
        }
        
        private object[] OnEndGetListOfVolunteerGroups(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> retVal = ((SOS.Phone.GroupServiceRef.GroupService)(this)).EndGetListOfVolunteerGroups(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetListOfVolunteerGroupsCompleted(object state) {
            if ((this.GetListOfVolunteerGroupsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListOfVolunteerGroupsCompleted(this, new GetListOfVolunteerGroupsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetListOfVolunteerGroupsAsync() {
            this.GetListOfVolunteerGroupsAsync(null);
        }
        
        public void GetListOfVolunteerGroupsAsync(object userState) {
            if ((this.onBeginGetListOfVolunteerGroupsDelegate == null)) {
                this.onBeginGetListOfVolunteerGroupsDelegate = new BeginOperationDelegate(this.OnBeginGetListOfVolunteerGroups);
            }
            if ((this.onEndGetListOfVolunteerGroupsDelegate == null)) {
                this.onEndGetListOfVolunteerGroupsDelegate = new EndOperationDelegate(this.OnEndGetListOfVolunteerGroups);
            }
            if ((this.onGetListOfVolunteerGroupsCompletedDelegate == null)) {
                this.onGetListOfVolunteerGroupsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListOfVolunteerGroupsCompleted);
            }
            base.InvokeAsync(this.onBeginGetListOfVolunteerGroupsDelegate, null, this.onEndGetListOfVolunteerGroupsDelegate, this.onGetListOfVolunteerGroupsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SOS.Phone.GroupServiceRef.GroupService CreateChannel() {
            return new GroupServiceClientChannel(this);
        }
        
        private class GroupServiceClientChannel : ChannelBase<SOS.Phone.GroupServiceRef.GroupService>, SOS.Phone.GroupServiceRef.GroupService {
            
            public GroupServiceClientChannel(System.ServiceModel.ClientBase<SOS.Phone.GroupServiceRef.GroupService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetListOfGroups(string SearchKey, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = SearchKey;
                System.IAsyncResult _result = base.BeginInvoke("GetListOfGroups", _args, callback, asyncState);
                return _result;
            }
            
            public SOS.Phone.GroupServiceRef.GroupList EndGetListOfGroups(System.IAsyncResult result) {
                object[] _args = new object[0];
                SOS.Phone.GroupServiceRef.GroupList _result = ((SOS.Phone.GroupServiceRef.GroupList)(base.EndInvoke("GetListOfGroups", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetListOfVolunteerGroups(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetListOfVolunteerGroups", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> EndGetListOfVolunteerGroups(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group> _result = ((System.Collections.ObjectModel.ObservableCollection<SOS.Phone.GroupServiceRef.Group>)(base.EndInvoke("GetListOfVolunteerGroups", _args, result)));
                return _result;
            }
        }
    }
}
